default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: password

development:
  <<: *default
  database: dummy_spec_dev

test:
  <<: *default
  database: dummy_spec_test